"""empty message

Revision ID: 3d565a17c399
Revises: 
Create Date: 2022-08-13 08:59:24.554314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d565a17c399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('artists', 'genres')
    op.add_column('venues', sa.Column('website', sa.String(length=300), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.drop_column('venues', 'genre')
    op.drop_column('venues', 'talent_seeking')
    op.drop_column('venues', 'weblink')
    op.drop_column('venues', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('weblink', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('talent_seeking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'website')
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('genres')
    # ### end Alembic commands ###
